# Generated by Django 4.0.2 on 2023-06-16 07:08

from django.db import migrations, models
import django.db.models.deletion
import portfolioApi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0002_remove_skillsection_id_remove_socialmedialinks_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReachOutForm',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioApi.base')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('query', models.TextField(blank=True, max_length=10000, null=True)),
                ('ad_source', models.CharField(blank=True, max_length=100, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reach Out Form',
                'verbose_name_plural': 'Reach Out Form',
            },
            bases=('portfolioApi.base',),
        ),
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioApi.base')),
                ('cv', models.FileField(blank=True, null=True, upload_to=portfolioApi.utils.cv_upload_path)),
            ],
            bases=('portfolioApi.base',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolioApi.base')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=portfolioApi.utils.testimonial_upload_photo)),
                ('company', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-weight'],
            },
            bases=('portfolioApi.base',),
        ),
        migrations.AddField(
            model_name='skillsection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=portfolioApi.utils.skill_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='aboutmesection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=portfolioApi.utils.aboutme_upload_logo),
        ),
        migrations.AlterField(
            model_name='jumbo',
            name='jumbo_img',
            field=models.ImageField(blank=True, null=True, upload_to=portfolioApi.utils.jumbo_upload_image),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=portfolioApi.utils.project_upload_logo),
        ),
        migrations.AlterField(
            model_name='servicesoffred',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=portfolioApi.utils.service_upload_icon),
        ),
        migrations.AddField(
            model_name='aboutmesection',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioApi.resumeupload'),
        ),
    ]
